import type { Metadata } from 'next';
import './globals.css';
import { inter, cabinetGroteskExtraBold } from '@/libs/fonts';
export const metadata: Metadata = {
  title: 'Spinel',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${cabinetGroteskExtraBold.variable} w-full min-h-screen bg-backgroundPrimary pt-[20px] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
